### ISSUE TITLE
A few fixes and upgrades

### ISSUE THREAD

**Issue by techpeace** [tsrivishnu/alexa-rails#12]
Howdy! I've been updating this library to get it functional with the latest API's [in our fork](https://github.com/voxable-labs/alexa-rails). If you're still maintaining or using this library, I'd be happy to split them up into PR's and send them back your way.

Thanks!

**Comment by tsrivishnu** [comment]
Hi,

I haven't been able to dedicate time for this library and also haven't been using it lately. I'm glad to see that you have some updates and fixes in your fork. 

I'm happy to merge them into the library if you could open PR's.

Thank you.

**Comment by techpeace** [comment]
No worries! I definitely understand. I'll open some new pull requests.

**Comment by tsrivishnu** [comment]
Thank you!
